#!/usr/bin/perl

    use strict;
    use warnings;

    use TreeTraversal;
    use Board;
    use Move;

    use Data::Dumper;

# level:  Tricky-11
my $board = new Board( width => 3, height => 3);

$board->cells->[2] = [qw[   2  -2   4 ]];
$board->cells->[1] = [qw[   5  -4   7 ]];
$board->cells->[0] = [qw[   6   2   2 ]];


my $move_list = TreeTraversal::IDDFS($board);

if (defined($move_list)) {
    TreeTraversal::display_solution($move_list, $board);
} else {
    print "No solution found.\n";
}
