#!/usr/bin/perl

    use strict;
    use warnings;

    use TreeTraversal;
    use Board;
    use Move;

    use Data::Dumper;

my $filename = shift
    or die "please specify the filename of a board to solve\n";

my $board = Board::new_from_file($filename);

$board->display;

my $move_list = TreeTraversal::IDDFS($board);

if (defined($move_list)) {
    TreeTraversal::display_solution($move_list, $board);
} else {
    print "No solution found.\n";
}
