#!/usr/bin/perl

# The main entry point.
# 
# Give it a board to solve, and it will start cranking away.

    use strict;
    use warnings;

    use TreeTraversal;
    use Board;
    use Move;

    use Time::HiRes qw( time );
    use Data::Dumper;

my $filename = shift
    or die "please specify the filename of a board to solve\n";

my $board = Board::new_from_file($filename);

$board->display;

my $started = time();
my $move_list = TreeTraversal::IDDFS($board);
my $elapsed = time() - $started;

if (defined($move_list)) {
    TreeTraversal::display_solution($move_list, $board);
    printf "Solution found in %.2f seconds.\n", $elapsed;
} else {
    print "No solution found.\n";
}
