#!/usr/bin/perl

# The main entry point.
# 
# Give it a board to solve, and it will start cranking away.

    use strict;
    use warnings;

    # FindBin replacement
    use Cwd 'abs_path';
    use File::Basename;
    use lib dirname( abs_path $0 );

    use TreeTraversal;
    use Board;
    use Move;

    use Time::HiRes qw( time );
    use Data::Dumper;

# we don't want to cover ALL possible 
my @bailiwick = keys %Board::to_fingerprint;
